# Generated by Django 4.0 on 2024-03-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
